muktihari/fit

proto/marshaler.go

When marshaling message number, it should choose which byte order to use instead of using little endian.
Decoder code block as a reference:
https://github.com/muktihari/fit/blob/d78e0791daaa1f48adec2f5e46139719084c148f/decoder/decoder.go#L401

fix(proto): message definition marshaler byte order

---

factory/exported_gen.go
factory/factory_gen.go
internal/cmd/fitgen/builder/shared/constant.tmpl
internal/cmd/fitgen/factory/factory.tmpl
profile/typedef/file_gen.go
profile/typedef/mesg_num_gen.go

Registering manufacturer-specific types and messages are no longer restricted to the manufacturer's range; however, it still complies with not modifying existing types or messages.
I see some manufacturers using `Message Number` outside the range `0xFF00-0xFFFE`, e.g. `68` on Fit files generated by Bryton. The number is not specified in `Profile.xlsx`, it's probably used for internal purpose by Garmin as the creator of the Fit Protocol and the manufacturers. The ability to define it outside range will benefit the engineers using this SDK for manufacturer specific purpose.

feat: register manufacturer-specific types and messages

---

decoder/decoder.go
decoder/decoder_test.go

- component expansion is no longer using map to hold the bit value since it will only hold containingField's value
- remove unecessary check on component.FieldNum, we have no invalid component.FieldNum in the factory

refactor(decoder): simplify component expansion

---

cmd/fitconv/csv/converter.go
encoder/encoder.go
proto/proto.go
proto/proto_test.go

BREAKING CHANGES:
- FieldByNum now returns one value instead of two, having multiple values does not make sense since the field will be nil anyway.
New Features:
- FieldValueByNum is added as a shortcut to retrieve field's value.

!feat(proto): method FieldByNum now returns one value, method FieldValueByNum is added.

---

cmd/fitactivity/README.md
cmd/fitactivity/combiner/combiner.go
cmd/fitactivity/concealer/concealer.go

- combine now calculates gap between sessions and add it to total_elapsed_time
- combine now updates session's end position with next files session's end position.
- conceal now updates session's start and end position  to match the new start and new end record.
- update README.md

fix(cli): fitactivity combine and conceal logic

---

docs/usage.md
profile/filedef/activity.go
profile/filedef/course.go
profile/filedef/filedef.go
profile/filedef/listener.go
profile/filedef/workout.go

- Course and Workout to proto.Fit convertion is now implemented
BREAKING CHANGES:
- `filedef.NewListener` is no longer receiving a pointer to the file, instead we only need to specify the file in generic constraint e.g.  `filedef.NewListener[filedef.Activity]()`

feat!: update filedef implementation

---

factory/factory_gen.go
internal/cmd/fitgen/factory/builder.go

The changes:
- Previously in the factory on `RecordMesg`, `compressed_speed_distance's Value` was `uint8(255)`, this is not correct since the field is an array `[3]uint8` field, now it is changed to `[]uint8(nil)`. This validator will handle this gracefully, while it is nil value but not a nil type so validator will not complain, and since it is a nil value, nothing will be written to the file on encoding process (marshal).
- We use slice as it is convenient to work with slices and for simplicity, it's user responsibility to validate the size of the slice, for the example above, it should match len 3. We encourage user to write a good code rather than having bunch of validators to validate all possibilities, we will provide verbose comment in our type declaration for helping user writing …

fix: factory array default value

---

cmd/fitconv/fitcsv/converter.go

typedef stringer is changed from previous refactor, previously it was returning the number of the constant `68` now it returning `MesgNumInvalid(68)` and fitconv has not handle this properly.

fix: fitconv on unknown message

---

encoder/validator.go
encoder/validator_test.go

In previous test, we did not check the size of the fields after validation and it turned out that value like `int`, `uint` and `struct{}` was silently skipped making it a false-negative. We should have returned an error to user but we kept encoding the FIT file with missing those message's fields.

fix: miss on encoder validate invalid value checking

---

encoder/validator.go
encoder/validator_test.go

- remove the need to allocate new slices improve the performance by an order of magnitude.
```
goos: darwin
goarch: amd64
pkg: github.com/muktihari/fit/encoder
│   old.txt    │               new.txt               │
│    sec/op    │   sec/op     vs base                │
Validate-4   147.70n ± 3%   40.28n ± 0%  -72.73% (p=0.000 n=10)
│  old.txt   │              new.txt               │
│    B/op    │   B/op     vs base                 │
Validate-4   64.00 ± 0%   0.00 ± 0%  -100.00% (p=0.000 n=10)
│  old.txt   │               new.txt               │
│ allocs/op  │ allocs/op   vs base                 │
Validate-4   1.000 ± 0%   0.000 ± 0%  -100.00% (p=0.000 n=10)
```

perf: improve validate mesg sec/op delta by -72%

---

proto/marshaler.go
proto/marshaler_test.go

Context: `MarshalBinary()`
- **Message Definition**: Reduce bytes alloc by directly append to `b`. For this case, there is no benefit on using `sync.Pool` since the bytes size is known at front, using `sync.Pool` will only add overhead.
- **Message**: Use `sync.Pool` to reduce memory usage and alloc since the method might be called thousands times, there is not much different in sec/op but memory usage is way reduced
```sh
goos: darwin
goarch: amd64
pkg: github.com/muktihari/fit/proto
│   old.txt    │               new.txt                │
│    sec/op    │    sec/op     vs base                │
MarshalMessageDefinition-4   731.2n ± 39%   242.2n ± 77%  -66.88% (p=0.000 n=10)
MarshalMessage-4             2.913µ ± 25%   2.724µ ± 23%        ~ …
```

perf: improve proto marshaler

---

decoder/accumulator.go
decoder/accumulator_test.go
decoder/decoder.go
decoder/decoder_test.go
encoder/encoder_test.go
encoder/validator.go
encoder/validator_test.go
factory/factory_gen.go
internal/cmd/fitgen/factory/builder.go
internal/cmd/fitgen/profile/builder.go
profile/typedef/unmarshal.go
profile/typedef/unmarshal_test.go
proto/proto.go

- decoder: use single backing array instead of creating slice on each r read since the max size is known.
- decoder: implement reuse existing variables/instance rather than creating new one.
- proto: remove Size in FieldBase, we can get the size from basetype.
- profile: clean up fitgen's profile builder.go
- generate: profile and factory
benchmark:
```js
goos: darwin
goarch: amd64
│    old.txt    │               new.txt                │
│    sec/op     │    sec/op     vs base                │
DecodeMessageData-4   11.317µ ± 13%   9.543µ ±  1%  -15.68% (p=0.000 n=10)
Decode-4               160.7m ± 44%   137.0m ± 11%  -14.76% (p=0.001 n=10)
geomean                1.349m         1.144m        -15.22%
│ …
```

perf: reduce decoder malloc & reuse existing vars

---

encoder/encoder.go
encoder/encoder_test.go
encoder/lru.go
encoder/lru_test.go

LRU implementation is extracted from inside Encoder to a new **lru** struct and it is now simplified for easier maintainability.  It easier to read, test and benchmark. The sec/op is pretty much similar but the B/op and allocs/op is slightly reduced.
benchstat:
```js
goos: darwin
goarch: amd64
pkg: github.com/muktihari/fit/encoder
│   old.txt    │              new.txt               │
│    sec/op    │   sec/op     vs base               │
Encode/normal_header_zero-4            80.07m ±  7%   79.36m ± 4%       ~ (p=0.063 n=10)
Encode/normal_header_15-4              81.42m ± 73%   80.19m ± 8%       ~ (p=0.247 n=10)
Encode/compressed_timestamp_header-4   72.55m ± 30%   72.38m ± 0%       ~ (p=0.123 n=10)
geomean                                77.91m …
```

perf: simplify encoder's LRU

---

cmd/fitconv/fitcsv/converter.go
decoder/accumulator.go
decoder/accumulator_test.go
decoder/bits.go
decoder/bits_test.go
decoder/decoder.go
decoder/decoder_test.go
kit/typeconv/typeconv.go
kit/typeconv/typeconv_test.go
proto/proto.go
proto/proto_test.go

- Now component expansion will expand the expanded component (the destination field) that can itself requiring expansion.
- The expanded component candidate's value now will be matched with the scale offset with the destination field.
- Accumulate and bits calculation is in uint32 since Profile.xlsx (on Bits's comment) says:
> "Current implementation only supports Bits value of max 32."
- When the implementation changes, for example supporting 64 bits, we can change it later.
- Field's `SubFieldSubtitution` method now returning single value (*subField) instead of two (*subField, bool), since it will be nil anyway if no SubField is found.
- Fix on `SubFieldSubtitution` should have continue to lookup instead of returning when 1 single map is not match.
- Now when creating fields slice, we …

fix: decoder on component expansion

---

encoder/encoder.go
encoder/lru.go

- This is not a bug but a potential bug (can cause panic index out of bound) if it's being abused when declaring unsupported header.Size, for example this crc calculation might cause panic `e.crc16.Write(b[:header.Size-2])` if the result of subtraction is negative, now we check the size early on and have fixed len `e.crc16.Write(b[:12])` since we now the exact len. Now we used explicit slice indexes for crc, was `b[header.Size-2:]` now `b[12:14]`. If user passing header.Size < 12 it will be replaced by default one (header with size = 14). We only guard against something that might cause panic, if user still passing wrong size intentionally, so be it, it will not cause panic or error, only the fit file might not be read by other decoder.
- Fix typo on lru's `Put` method's docs.

chore: clean up encoder

---

internal/cmd/fitgen/profile/mesgdef/builder.go
internal/cmd/fitgen/profile/mesgdef/data.go
internal/cmd/fitgen/profile/mesgdef/mesgdef.tmpl
profile/mesgdef/ant_rx_gen.go
profile/mesgdef/ant_tx_gen.go
profile/mesgdef/event_gen.go
profile/mesgdef/exd_data_concept_configuration_gen.go
profile/mesgdef/exd_data_field_configuration_gen.go
profile/mesgdef/hr_gen.go
profile/mesgdef/jump_gen.go
profile/mesgdef/lap_gen.go
profile/mesgdef/length_gen.go
profile/mesgdef/monitoring_gen.go
profile/mesgdef/record_gen.go
profile/mesgdef/segment_lap_gen.go
profile/mesgdef/segment_point_gen.go
profile/mesgdef/session_gen.go

- When creating any of mesgdef struct, we track which field is generated from component expansion so when we encode it again, we can omit the expanded fields.

feat: mesgdef now track fields from component expansion

---

encoder/encoder.go
encoder/encoder_test.go
profile/basetype/basetype.go
proto/proto.go
proto/proto_test.go

- Encoder was not set `endianness` before encoding message, causing all message would not be encoded in little-endian byte order even thought **WithBigEndian()** option is specified.
- Fix typo `endianess` should be `endianness`, missing `n` word

fix: encoder endianness

---

decoder/decoder.go
decoder/decoder_test.go
docs/usage.md

Why we need this and the best practices on when to use it is specified on https://developer.garmin.com/fit/cookbook/isfit-checkintegrity-read/

feat: add CheckIntegrity method on Decoder

---

encoder/encoder_test.go
encoder/validator.go
encoder/validator_test.go

Previously, we don't validate a string or []string to be a valid UTF-8 string representative before encoding, this may cause invalid FIT file when user accidentally encode non UTF-8 string as field's value. This should fix the potential issue that may arise.

fix: encoder should validate UTF-8 string

---

decoder/decoder.go
decoder/decoder_test.go
docs/usage.md

- CheckIntegrity sequence completed and any error encountered. sequence completed is useful to know how many FIT sequences are valid so we can recover it.
- Reduce alloc on initDecodeHeaderOnce() by inlining the function and variable.
- Move header validity order, should be check FileHeader's Size and bytes 8-12 first so we can sure that it's a FIT file, then we validate the other values.

feat: decoder CheckIntegrity now return two values

---

decoder/decoder_test.go
decoder/raw.go
decoder/raw_test.go
docs/usage.md

The idea is to allow us to use a minimal viable decoder for performance and memory-critical situations, where every computation or memory usage is constrained. RawDecoder itself is using constant memory < 131 KB and the Decode method has zero heap alloc (except errors) while it may use additional small stack memory. The implementation of the callback function is also expected to have minimal overhead. Theoretically, from the memory usage alone, this can run on an embedded device, for instance, using [tinygo](https://tinygo.org) or other compilers, but no attempt has been made.

feat: add raw decoder

---

decoder/decoder.go
decoder/decoder_test.go
docs/usage.md
encoder/lru.go
encoder/lru_test.go
profile/basetype/basetype.go
proto/marshaler.go

The optimizations are mostly targeting decoding or encoding FIT File using `localMessageNum 0` (for both normal header or compressed timestamp header).
Here is the benchstat when decoding `testdata/from_official_sdk/activity_lowbattery.fit` (since it uses `localMessageNum 0`):
```js
goos: darwin
goarch: amd64
│  old2.txt   │              new2.txt               │
│   sec/op    │   sec/op     vs base                │
Decode-4   13.58m ± 3%   11.97m ± 4%  -11.88% (p=0.000 n=10)
│   old2.txt   │              new2.txt               │
│     B/op     │     B/op      vs base               │
Decode-4   5.298Mi ± 0%   5.297Mi ± 0%  -0.03% (p=0.000 n=10)
│  old2.txt   │              new2.txt              │
│ …
```

perf: micro optimizations

---

encoder/encoder.go
encoder/encoder_test.go
proto/marshaler.go
proto/proto.go

This is a huge improvement as we reduce 99.99% allocations reducing GC overhead as well as we got improvement in sec/op 12.82% overall 🚀
benchstat:
```js
goos: darwin
goarch: amd64
pkg: github.com/muktihari/fit/encoder
│    old.txt    │               new.txt                │
│    sec/op     │    sec/op     vs base                │
Encode/normal_header_zero-4                     88.13m ± 12%   88.32m ± 64%        ~ (p=0.912 n=10)
Encode/normal_header_15-4                      101.01m ± 13%   81.96m ± 17%  -18.86% (p=0.023 n=10)
Encode/compressed_timestamp_header-4            75.24m ±  3%   73.90m ± 62%        ~ (p=0.353 n=10)
EncodeWriterAt/normal_header_zero-4             58.24m ± 23%   42.92m ± 19%  -26.30% (p=0.011 n=10) …
```

perf: encoder reduce allocs

---

decoder/accumulator_test.go
decoder/decoder.go
decoder/decoder_test.go
encoder/encoder.go
encoder/encoder_test.go
encoder/lru.go
encoder/lru_test.go
encoder/stream.go
encoder/stream_test.go
encoder/validator.go
proto/validator.go
proto/validator_test.go

Now Decoder and Encoder have the ability to Reset, the underlying storage will be reused reducing memory allocation.
benchmark:
```js
goos: darwin
goarch: amd64
BenchmarkReset/benchmark_New()-4          419300        2475   ns/op      9632 B/op       6 allocs/op
BenchmarkReset/benchmark_Reset()-4       6264751         207.6 ns/op       120 B/op       3 allocs/op
```
```js
goos: darwin
goarch: amd64
pkg: github.com/muktihari/fit/encoder
BenchmarkReset/benchmark_New()-4          1000000      1155   ns/op       2283 B/op      13 allocs/op
BenchmarkReset/benchmark_Reset()-4        6866968       168.6 ns/op         97 B/op       3 allocs/op
```

feat: add ability to reset so the object can be reused

---

encoder/validator.go
encoder/validator_test.go
profile/typedef/marshal.go
profile/typedef/marshal_test.go
profile/typedef/typedef.go
profile/typedef/typedef_test.go
proto/proto.go

Now encoder's validator will validate the `n of fields`, `n of developer fields` as well as size of its value in bytes should not exceed 255. We are more confident in the resulting FIT file validity.

feat: add size validation on encode

---

decoder/decoder.go
decoder/decoder_test.go
factory/factory_gen.go
internal/cmd/fitgen/factory/builder.go
proto/proto.go

Let's assume we compile our program for 64 bit machine, which memory block is every 8 bytes.
Previously, we have this proto.FieldBase struct having  112 bytes as follows:
```go
type FieldBase struct {
Name       string // 16
Num        byte // 1
Type       profile.ProfileType // 2
Array      bool // 1
// +4 padding bytes
Scale      float64 // 8
Offset     float64 // 8
Units      string // 16
Accumulate bool // 1
// +7 padding bytes
Components []Component // 24
SubFields  []SubField // 24
}
```
By re-arrange the struct order, we can save 8 bytes, so the size is now 104 bytes per proto.FieldBase:
```go
type FieldBase struct {
Name       string // 16
Num        byte // 1
Type       profile.ProfileType // 2
Array      bool // 1
Accumulate bool // 1
// +3 padding bytes 
Scale      float64 // 8 …
```

perf: proto memory alignment

---

cmd/fitconv/fitcsv/converter.go
decoder/decoder.go
decoder/decoder_test.go
decoder/raw_test.go
encoder/encoder_test.go
encoder/validator.go
encoder/validator_test.go
factory/factory_gen.go
internal/cmd/fitgen/factory/builder.go
internal/cmd/fitgen/profile/builder.go
internal/cmd/fitgen/profile/data.go
internal/cmd/fitgen/profile/profile.tmpl
profile/profile_gen.go
proto/proto.go
proto/proto_test.go

Changes:
- FieldBase now has dedicated BaseType field instead of derive it from Type (ProfileType)
Deriving `BaseType` from `ProfileType` consume small amount of CPU time since it needs to go through a switch with 196 cases (our current number of ProfileType). The accumulated time will become significant as the number of messages in the FIT file increased. Moreover, BaseType is used more frequently than ProfileType, so it makes sense to have a dedicated field for it.
- Add new function `profile.ProfileTypeFromBaseType` to make ProfileType more efficient instead of using `profile.ProfileTypeFromString`
- DeveloperField Type is renamed to BaseType since it's a BaseType
This change is to make our code consistent on naming BaseType.

feat(proto)!: update on FieldBase and DeveloperField

---

encoder/encoder.go
encoder/lru.go
encoder/validator.go
proto/marshaler.go

1. proto
- Add WriteTo method to FileHeader to avoid alloc when marshaling.
2. encoder
- Reduce 1 alloc from marshaling FileHeader and reduce 1 more alloc from encoding CRC.
- Simplify validator code, early return when valid len(fields) > 255
- Remove slices package from lru.go, use bytes.Equal instead to check item's equality

perf: reduce encoder memory alloc

---

factory/factory_gen.go
internal/cmd/fitgen/factory/factory.tmpl

- There is no need to check if `registeredMesgs` is nil when read data from it and only check nil when writing on it. A nil map will automatically return zero value on read and only panic on write.

chore: simplify factory code

---

factory/exported_gen.go
factory/factory_gen.go
internal/cmd/fitgen/factory/builder.go
internal/cmd/fitgen/factory/factory.tmpl

- Use [256]proto.Field in the predefined message in the factory for fast look up, this ensure O(1) look up when creating Field instead of looping to get the Field like previous version.
- Since the predefined messages in factory is now using fixed array, the behavior of `CreateMesg` is slightly changed since we need to populate the slice for the returned message's fields. It will populate the data once during the first invocation, since this method is not used either by the decoder or the encoder it should be fine, method documentation is updated to make users aware about this change in case users want to use this method.
```js
goos: darwin
goarch: amd64
│   old.txt   │               new.txt …
```

perf: optimize factory performance

---

factory/factory_gen.go
internal/cmd/fitgen/factory/builder.go
internal/cmd/fitgen/factory/factory.tmpl

- Previously we use concret values for fields in message struct, using `unsafe.Sizeof(mesgs)`, it will produce 3362000 B (3.36 MB)
```go
type message struct {
Num    typedef.MesgNum
Fields [256]proto.Field
}
var mesgs = [...]message{ /* data */ }
```
- We change it to use pointer values since most of the message only has small amount of fields, it will only produce 842960 (0,84 MB)
```go
type message struct {
Num    typedef.MesgNum
Fields [256]*proto.Field // <---- this
}
```
There is no significant performance reduction on decoding process after factory uses pointer values
```js
goos: darwin
goarch: amd64
│   new.txt   │           new2.txt            │
│   sec/op    │   sec/op     vs base          │ …
```

perf: reduce factory memory usage

---

internal/cmd/fitgen/parser/parser.go

Resolve https://github.com/muktihari/fit/security/code-scanning/26
This does not change the current generated files, so no release needed. This change ensure future profile update to be correct, any typo related to this integer conversion in `Profile.xlsx` from official release (or `Product Profile` specified by user) will be spotted right away instead of silent error, even thought the chance is pretty low.

fix: potential incorrect string to integer conversion

---

proto/proto.go
proto/proto_test.go

The value should be calculated from DeveloperField.Value and DeveloperField.BaseType using proto.Sizeof.

fix: wrong 'Size' value when creating mesgDef from mesg

---

encoder/validator.go
encoder/validator_test.go
internal/cmd/fitgen/profile/mesgdef/builder.go

Currently, in Profile.xlsx (v21.133) there is no field with scale == 1 and offset other than 0, but in case it happen, this following code in `encoder/validator.go` is problematic, if scale is 1 and offset is 20 then it become `false && true` -> `false`
```go
if field.Scale != 1 && field.Offset != 0 { }
```
- Verify and fix similar logic across files.

fix: potential bug on scale offset logic

---

decoder/decoder_test.go
encoder/encoder.go
encoder/encoder_test.go
internal/cmd/fitgen/profile/builder.go
internal/cmd/fitgen/profile/data.go
internal/cmd/fitgen/profile/profile.tmpl
profile/profile_gen.go
profile/version_gen.go

Remove Version() and  export the Version constant directly, so we can retrieve the version at compile time.

fix: remove profile.Version() and export Version constant instead

---

profile/basetype/basetype.go
proto/value.go

In proto.Unmarshal, the SDK will remove any UTF-8 Null-Terminated String (0x00) from the string or []string value. To make consistency on how we should treat strings, all functions or methods that returning strings should return strings without `0x00`, and all functions or methods that validate invalid strings should check for both empty string and `0x00`, invalid if the result of this is true -> `value == "" || value == "\x00"`. 
Value marshaler will check whether a string is end with `0x00`, if it does not end with `0x00` will automatically add it. If the users intentionally add multiple `0x00` it should allow it. In cases where message definitions differ only slightly, such as when creating FieldDescription messages with minor variations in the FieldName value (type: []string), it make …

fix: consistency on treating invalid strings

---

decoder/decoder.go
decoder/decoder_test.go
docs/usage.md

There is a case where a FIT file from a well-known brand contains fieldDef's Size mismatch with fieldDef's Basetype.Size(): Size is 1 byte but the type is uint32 which should have been 4 bytes. This cause panic in our current implementation since the binary unmarshaler will try to unmarshal 4 bytes but we got only 1 byte in []byte slice, index out of bound. 
Actually, we do not want to support bad encoded FIT file as there might be too many cases to handle and adding complexity to our code. However, this bug causes panic in our FIT SDK so we need to take a measurement and gracefully handle such cases. 
Returning an error is one of the options, but then we can't get the FIT file contents at all, so let's make a simple workaround to handle that so we could retrieve the contents as much as …

fix: decoder now handle bad encoded fit file when size < basetype.Size

---

decoder/decoder.go
decoder/decoder_test.go
decoder/raw_test.go
docs/usage.md
encoder/encoder.go
encoder/encoder_test.go
kit/hash/crc16/crc16.go
kit/hash/crc16/crc16_test.go

BREAKING CHANGES:
- `MakeFitTable` renamed to `MakeFITTable`
Benchmark:
```js
goos: darwin
goarch: amd64
pkg: github.com/muktihari/fit/kit/hash/crc16
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
Write-4   27.82µ ± 0%   21.55µ ± 0%  -22.53% (p=0.000 n=10)
│  old.txt   │            new.txt             │
│    B/op    │    B/op     vs base            │
Write-4   0.000 ± 0%   0.000 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
│  old.txt   │            new.txt             │
│ allocs/op  │ allocs/op   vs base            │
Write-4   0.000 ± 0%   0.000 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
```
close #180

perf!: reduce crc16 pointer dereference

---

decoder/decoder.go
decoder/decoder_test.go
decoder/readbuffer.go
decoder/readbuffer_test.go

Benchmark:
```js
goos: darwin
goarch: amd64
│   old.txt    │              new.txt               │
│    sec/op    │   sec/op     vs base               │
Decode-4   105.75m ± 1%   99.00m ± 3%  -6.39% (p=0.000 n=10)
│   old.txt    │            new.txt             │
│     B/op     │     B/op      vs base          │
Decode-4   73.49Mi ± 0%   73.49Mi ± 0%  ~ (p=0.050 n=10)
│   old.txt   │             new.txt             │
│  allocs/op  │  allocs/op   vs base            │
Decode-4   100.0k ± 0%   100.0k ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
```
close #179

pref: implement readBuffer to eliminate extra copying

---

decoder/decoder.go
decoder/decoder_test.go
decoder/raw.go

- Previously, panic will occur on `proto.Unmarshal` if field definition's size is zero and `field.Array` is false. When `field.Array` is true, `proto.Unmarshal` will return empty slice which is an undefined behavior. A checker to check the size before unmarshal is now implemented: if size is zero, the field/developerField will be skipped. New log message is added to print the warning (only if `logWriter` is not nil).
- Now log will only print if `logWriter` is not nil, previously it was printing to `io.Discard` which will do unnecessarily formatting that consume additional CPU time.
- Fix `RawDecoder` should reset local message definitions after a sequence is completed.
- Gracefully handle poorly encoded FIT file on `decodeDeveloperFields` too just like on `decodeFields`.
- Clean up code.

fix: gracefully handle poorly encoded FIT file to prevent panic.

---

cmd/fitconv/main.go
decoder/decoder.go
decoder/decoder_test.go
decoder/listener.go
profile/filedef/activity_test.go
profile/filedef/listener.go
profile/filedef/listener_test.go
profile/filedef/monitoring_ab_test.go

Background: #182 
BREAKING CHANGES:
- By default, Decoder no longer copy the message before send it to listeners for efficiency, the lifecycle of the mesg is only guaranteed before `OnMesg` method returns so any listener that process the message concurrently should copy the mesg before return. For legacy behavior (<= v0.14.0), use `decoder.WithBroadcastMesgCopy()`
What's Changed:
- `filedef's Listener` now copy the mesg before processing it concurrently to accommodate the behavior change. It copies the mesg using pool of reusable messages to reduce alloc.
Benchmark:
```js
goos: darwin
goarch: amd64
│   old.txt    │               new.txt                │
│    sec/op    │    sec/op     vs base …
```

refactor!: change decoder's listener behavior

---

internal/cmd/csvdiff/main.go
internal/cmd/testgen/big_activity.go
internal/cmd/testgen/main.go

No need to release, no functionality change, only update internal CLIs for debugging:
- csvdiff: fix `splitByField`'s bad loop on iterating splitted values
- testgen: fix `len(fit.Messages)` size mismatch, no need to regenerate test files, small diff only.

chore: fix internal cli: csvdiff, testgen

---

cmd/fitdump/README.md
cmd/fitdump/main.go

The purpose is to represent bytes per segment for low-level debugging.

cli: add fitdump for dumping bytes segments

---

internal/cmd/fitgen/profile/mesgdef/builder.go
internal/cmd/fitgen/profile/mesgdef/data.go
internal/cmd/fitgen/profile/mesgdef/mesgdef.tmpl
profile/mesgdef/device_info_gen.go
profile/mesgdef/dive_settings_gen.go
profile/mesgdef/event_gen.go
profile/mesgdef/file_id_gen.go
profile/mesgdef/lap_gen.go
profile/mesgdef/mesg_capabilities_gen.go
profile/mesgdef/monitoring_gen.go
profile/mesgdef/one_d_sensor_calibration_gen.go
profile/mesgdef/schedule_gen.go
profile/mesgdef/segment_lap_gen.go
profile/mesgdef/session_gen.go
profile/mesgdef/slave_device_gen.go
profile/mesgdef/three_d_sensor_calibration_gen.go
profile/mesgdef/training_file_gen.go
profile/mesgdef/watchface_settings_gen.go
profile/mesgdef/workout_step_gen.go

Example: Product accessor on FileId
```go
// GetProduct returns Dynamic Field interpretation of Product. Otherwise, returns the original value of Product.
//
// Based on m.Manufacturer:
//   - name: "favero_product", value: typedef.FaveroProduct(m.Product)
//   - name: "garmin_product", value: typedef.GarminProduct(m.Product)
//
// Otherwise:
//   - name: "product", value: m.Product
func (m *FileId) GetProduct() (name string, value any) {
switch m.Manufacturer {
case typedef.ManufacturerFaveroElectronics:
return "favero_product", typedef.FaveroProduct(m.Product)
case typedef.ManufacturerGarmin, typedef.ManufacturerDynastream, typedef.ManufacturerDynastreamOem, typedef.ManufacturerTacx:
return "garmin_product", typedef.GarminProduct(m.Product)
}
return "product", m.Product
}
```

feat(mesgdef): add dynamic field accessor

---

.github/workflows/scorecard.yml

This reverts commit f4be21402c3f4383bea5c546713a6cbde73063e8.
Unexpected error:
2024/04/23 09:44:35 error sending scorecard results to webapp: http response 400, status: 400 Bad Request, error: {"code":400,"message":"workflow verification failed: imposter commit: 8f596b4ae3cb3c588a5c46780b86dd53fef16c52 does not belong to github/codeql-action/upload-sarif, see https://github.com/ossf/scorecard-action#workflow-restrictions for details."}

Revert "chore(deps): bump github/codeql-action from 3.25.1 to 3.25.2 (#210)"

---

.github/workflows/scorecard.yml

This reverts commit 12ad7c479fbfbac354e2cf06312070483f52d23c.
The problem has been resolved. Ref: https://github.com/github/codeql-action/issues/2257

chore(deps): bump github/codeql-action from 3.25.1 to 3.25.2

---

decoder/decoder.go
decoder/decoder_test.go
decoder/raw.go
decoder/raw_test.go

- When `d.fileHeader.CRC == 0x0000`, it means the FIT file might be using legacy header (12 bytes) so there is no crc integrity for the `file_header`. However, the `file_crc` that will validate the integrity of the messages should be present. We should reset the `d.crc16` before returning nil, otherwise the calculation of the messages' crc might mismatch since `d.crc16` is still containing file_header's crc calculation. (We don't need reset `d.crc16` on error)
- Clean up decoder's code

fix(decoder): should reset crc16 when file's crc is 0

---

cmd/fitprint/printer/printer.go
profile/filedef/listener.go

- Fix wrong re-slicing that causing inconsistent data
- Filedef's Listener **_must clone_** DeveloperFields since on mesgdef's struct creation, it's being referenced only, not copied.

fix: listener object pooling

---

decoder/decoder_test.go
decoder/readbuffer.go
decoder/readbuffer_test.go

- Fix readbuffer wrong buf positions when reader return io.EOF, buf positions should not be changed in such event.
- Add scenario test to ensure the correctness of readbuffer such as when check integrity + decode.
- Improve benchmark tests

fix: decoder readbuffer when reader is reset

---

factory/factory_gen.go
internal/cmd/fitgen/factory/factory.tmpl

- Fix factory's CreateMesg missing bound check before accessing array which may cause panic index out of range.
- Change protoMesgs array to slice so we don't use memory when it's not populated.

fix: factory's CreateMesg missing bound check

---

profile/basetype/basetype.go
profile/basetype/basetype_test.go

When receiving bad encoded FIT file such as this bytes stream `[]byte("\x0e\x10^\x06\x17\b\x00\x00.FIT\xe3\xbb@0000\x060000000000000000000")`, It has fieldDef with invalid BaseType causing our decoder to panic when doing this operation `fieldDef.Size%fieldDef.BaseType.Size()` since Size will return 0. To avoid this, let's make invalid size to be 255 just like all invalid values is the max size of the types. Any value modulo by 255 is always the value itself and any value divided by 255 will always zero.

fix: decoder integer divide by zero on invalid basetype

---

decoder/decoder.go
decoder/decoder_test.go
profile/basetype/basetype.go
profile/basetype/basetype_test.go

When encountering invalid `basetype` on decoding message definition's field definition, decoder now will return a error instead of undefined behavior. If the field is a known field, actually we could use `basetype` from the factory, however, the correctness of the data is still questionable, let's just make it fail since most cases bad encoded FIT files are corrupt anyway.
Another changes:
- basetype: add `Valid` method to check whether the basetype is valid or not.
- decoder: remove sentinel error `ErrByteSizeMismatch` since it's not used anywhere.
- decoder: add sentinel error `ErrInvalidBaseType`

fix: decoder on handling invalid basetype

---

proto/value_marshal.go
proto/value_marshal_test.go

When string slice value is empty, `lenof` will return 1 for 0x00 (null-terminated string), however value marshal did not add the 0x00 value. And if message validator with perverse invalid value is enabled, it will lead to a corrupted FIT file.

fix: proto value marshal empty string slice

---

decoder/decoder.go
decoder/decoder_test.go

When encountering compressed timestamp message but the message is unknown (it could be manufacturer specific message), the field become unknown as well, in such cases, we must assign the `BaseType` and `Type` to `uint32` so that the resulting decoded FIT can be encoded as per original instead of returning error in encoder since the `BaseType` was set to default value: `Enum`.

fix: decoder handle compressed timestamp for unknown field

---

proto/value_unmarshal.go
proto/value_unmarshal_internal_test.go

fix: proto value unmarshal strings as utf8 string

---

cmd/fitconv/README.md
cmd/fitconv/main.go

- `fitconv` now will always produce csv files regardless decode return with error or not, so we could retrieved the data.
- By default, `fitconv` will not check crc checksum since most cases we use `fitconv` for debugging. However, `-checksum` option is now provided if user want to perform the checksum.

cli: update fitconv

---

decoder/bits.go
decoder/readbuffer.go
decoder/readbuffer_test.go

- readBuffer's minReadBufferSize should at least 765 since max value of decoder read from reader is 765, otherwise, readBuffer will always return ErrShortBuffer when n read is > 16 (previous minReadBufferSize).
- on reset readBuffer, only when size > oldsize we will allocate new slice, otherwise reuse existing by reslice.
- chore: rename `size` constant to `bitSize` in bits.go to reduce the constant being shadowed or potential misuse.

fix: update readbuffer minReadBufferSize

---

cmd/fitconv/fitcsv/lookup_gen.go
docs/generating_code.md
docs/runtime_registration.md
docs/usage.md
factory/factory_gen.go
go.mod
go.sum
internal/cmd/fitgen/parser/parser.go
profile/mesgdef/accelerometer_data_gen.go
profile/mesgdef/barometer_data_gen.go
profile/mesgdef/gyroscope_data_gen.go
profile/mesgdef/magnetometer_data_gen.go
profile/mesgdef/obdii_data_gen.go
profile/mesgdef/record_gen.go
profile/mesgdef/time_in_zone_gen.go
profile/typedef/connectivity_capabilities_gen.go
profile/typedef/exd_data_units_gen.go
profile/untyped/fieldnum/fieldnum_gen.go

`Profile.xlsx` is containing misspell such as:
Types:
- "connect_iq_app_managment" -> "managment" is a misspelling of "management"
- "degrees_farenheit" -> "farenheit" is a misspelling of "fahrenheit"
Messages:
- "cadence_zone_high_bondary" -> "bondary" is a misspelling of "boundary"
This cause misspelling issues on our generated code, this could lead to breaking our SDK since we rely on the `Profile.xlsx`, for example:
- "connect_iq_app_managment" will genenate constant `ConnectivityCapabilitiesConnectIqAppManagment`, when Garmin fixes the `Profile.xlsx` the spelling issue, the generated constant will be changed to `ConnectivityCapabilitiesConnectIqAppManagement`. When users use the constant in some versions, their code will break on newer version after the update. We should avoid this …

fix!: misspell on generated code due to Profile.xlsx's misspell issue

---

decoder/decoder.go
decoder/decoder_test.go
proto/value_unmarshal.go
proto/value_unmarshal_test.go

Previously, `proto.UnmarshalValue` will treat boolean as uint8 (or []uint8) due to there is no basetype.Bool in FIT basetypes, moreover it does not have context regarding `ProfileType` (in this case: `profile.Bool`). This creates invalid values when we convert proto.Value into bool (or []bool) such as in mesgdef. Now, `proto.UnmarshalValue` will receive `ProfileType` as parameters so it has the context to handle that special case.
Breaking Change: The signature of exported function, `proto.UnmarshalValue` is changed by having additional `ProfileType` parameter.

fix!: unmarshal boolean value should produce bool(s) instead of uint8(s)

---

proto/value_marshal.go
proto/value_marshal_test.go
proto/value_unmarshal.go

Sample Benchmark:
```js
goos: darwin
goarch: amd64
pkg: github.com/muktihari/fit/proto
│ valueold.txt │             valuenew.txt             │
│    sec/op    │    sec/op     vs base                │
ValueMarshalAppend-4    160.8n ± 4%   100.9n ± 12%  -37.27% (p=0.000 n=10)
│ valueold.txt │          valuenew.txt          │
│     B/op     │    B/op     vs base            │
ValueMarshalAppend-4     0.000 ± 0%   0.000 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
│ valueold.txt │          valuenew.txt          │
│  allocs/op   │ allocs/op   vs base            │
ValueMarshalAppend-4     0.000 ± 0%   0.000 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
```

perf: improve marshal and unmarshal slice value

---

decoder/decoder.go
decoder/decoder_test.go

- When developer data does not have DeveloperDataId reference, the decoder will try to write log to notify users that the decoder FIT file missing DeveloperDataId (he decoder will only log when logWriter is specified though). From the beginning, the decoder only using FieldDescription messages to decode the developer data, so the data can still be retrieved without error, however having the log as notification can help users debug the FIT file.
- Make decodeFileHeaderOnce func into method, this way we avoid one allocation and simplifying our code.
- Re-arrange decoder's methods order for readability, easier to maintain.
- Decoder will no longer call proto.LocalMesgNum, instead the code logic is copied directly to decoder to avoid bounds check, since compiler could not ensure that the …

fix: decoder on handling developer data and other improvements

---

cmd/fitactivity/combiner/combiner.go
decoder/decoder.go
encoder/encoder.go
encoder/validator.go
factory/factory_gen.go
internal/cmd/fitgen/factory/factory.tmpl
proto/proto.go
proto/validator.go
proto/value_marshal.go
proto/version.go

Previously:
```go
// decoder/decoder.go
var ErrCRCChecksumMismatch = errors.New("crc checksum mismatch")
```
```go
func init() {
decoder.ErrCRCChecksumMismatch = nil // allowed :(
}
```
Imagine we have a service for testing FIT file integrity, however, without our knowing, there is another library that silently altering the value, this way we will never get "mismatch" error as the value is now become nil. This will be hard to debug; more importantly, it might pose a security vulnerability.
Now since we change ErrCRCChecksumMismatch as unexported "errorString" string typed constant, the value will never be altered.
```go
// decoder/decoder.go
type errorString string
func (e errorString) Error() string { return string(e) }
const ErrCRCChecksumMismatch = errorString("crc checksum mismatch") …
```

chore: make all sentinel errors constant

---

encoder/encoder.go
encoder/encoder_test.go
encoder/lru.go
encoder/lru_test.go

- Fix  compress timestamp in header: 
Previously, we measure rollover event every > 32 seconds where it should be >= 32 seconds. This created the 32 seconds rollover to have timeoffset 0. When this message is decoded, most likely this message would have the same timestamp as the previously decoded message (at least our FIT SDK's decoder handle this way). 
- Fix lru on ResetWithSize
Previously, when reset with new size > than previous size, only `items` field would be re-allocated as the new size where `bucket` will be allocated automatically by `append`. This does no create any significant issue, however, this was not intended since `cap(bucket)` can be bigger than `cap(items)` as `append` will typically re-allocate doubling the previous cap or round it in a multiple of 8: 8, 16, etc …

fix: encoder compress timestamp

---

decoder/decoder.go
decoder/decoder_test.go
decoder/readbuffer.go

- Creating default options is no longer allocate since now we return value instead of pointer, and decoder's options field is now a concrete value as well. Decoder instance will be heap allocated anyway, it's better to have one big struct. 
- Now calling Reset() do not allocate.

perf: decoder options is no longer allocate

---

encoder/encoder.go
encoder/encoder_test.go
encoder/validator.go
encoder/validator_test.go

- defaultOptions and defaultValidatorOptions are now returning concrete value, and encoder's options field and messageValidator's options field are now concrete values as well. Encoder's mesgDef is now a concrete value to reduce another heap allocated object. Encoder and messageValidator instances will be heap allocated anyway, it's better to have one big struct. This reduce allocated object when creating and resetting the instances.
- Reset() object allocation reduced to 1 alloc, we can't make zero alloc since we let user to create their own implementation of MessageValidator through Option, so this object will always alloc.
- Fix misspelled words on encoder_test.go

perf: encoder options and validatorOptions are no longer allocate

---

decoder/decoder.go

- overrideStringArray should only override isArray when basetype is string.

fix: decoder developer field string handler

---

profile/filedef/activity.go
profile/filedef/activity_summary.go
profile/filedef/blood_pressure.go
profile/filedef/course.go
profile/filedef/device.go
profile/filedef/filedef.go
profile/filedef/filedef_test.go
profile/filedef/goals.go
profile/filedef/monitoring_ab.go
profile/filedef/monitoring_daily.go
profile/filedef/schedules.go
profile/filedef/segment.go
profile/filedef/segment_list.go
profile/filedef/settings.go
profile/filedef/sport.go
profile/filedef/totals.go
profile/filedef/weight.go
profile/filedef/workout.go

- Remove the usage of `filedef.ToMesgs` func in filedef and use loop directly, so we have less dependency code.
- Mark `filedef.ToMesg` interface and `filedef.ToMesgs` func as deprecated as it is no longer used, these can be removed in the next major/minor release. These items does not add any significant value, by removing it, we have less code to maintain.

chore: filedef clean up code

---

decoder/decoder.go
decoder/decoder_test.go

CheckIntegrity is a standalone method so it should not remember error, otherwise the decoder could not be reused. On previous version, users need to call Reset() to be able to reuse the Decoder but this was not what we intended.

fix: decoder's CheckIntegrity should not remember error

---

encoder/encoder.go
encoder/encoder_test.go

Previously, Reset() does not assign the new writer properly, so encoder still refer to the old writer.

fix: encoder reset did not assign new writer

---

encoder/encoder.go
encoder/encoder_test.go

- defaultOptions will no longer create new instance of message validator, instead, Reset() will take over the responsibility to check whether we actually need to create new instance of message validator (default) or when we can just use the message validator specified by users.
- New() will no longer directly assign Writer ensuring that we only have one path to assign Writer: via Reset(); This is to reduce the likelihood of making mistakes when implementing the code.

perf: remove unnecessary alloc on (*Encoder).Reset()

---

kit/datetime/datetime.go
kit/datetime/datetime_test.go

When user specified time before epoch, for instance "10 Nov 1945", an invalid uint32 will be returned.

fix: datetime's ToUint32 when time arg is before epoch

---

profile/filedef/activity_test.go
profile/filedef/filedef.go
profile/filedef/filedef_test.go
proto/proto.go

All timestamp fields should have num 253, except for these two messages that have different num due to the messages may have been added before the rule was put in place:
- Course Point's Timestamp num: 1
- Set's Timestamp num: 254
However, we don't see Official SDK implementations making exception regarding this, such as when decoding and encoding compressed timestamp, only messages that have timestamp num 253 are eligible for that feature.
We still need to sort those messages based on timestamp though, so  `filedef.SortMessagesByTimestamp` should handle it accordingly.
Ref: https://forums.garmin.com/developer/fit-sdk/f/discussion/311106/why-has-course_point-message-a-timestamp-field-1-and-not-253

fix: update rule regarding field num timestamp

---

cmd/fitactivity/README.md
cmd/fitactivity/combiner/combiner.go

When FIT files contains SplitSummary messages, the combined FIT file could not be uploaded to Garmin Connect. The workaround is to not including SplitSummary messages from the next FIT files.

cli: fitactivity fix combined FIT unable to upload to Garmin Connect

---

profile/filedef/activity.go
profile/filedef/activity_summary.go
profile/filedef/blood_pressure.go
profile/filedef/course.go
profile/filedef/device.go
profile/filedef/goals.go
profile/filedef/listener.go
profile/filedef/monitoring_ab.go
profile/filedef/monitoring_daily.go
profile/filedef/schedules.go
profile/filedef/segment.go
profile/filedef/segment_list.go
profile/filedef/settings.go
profile/filedef/sport.go
profile/filedef/totals.go
profile/filedef/weight.go
profile/filedef/workout.go

- Listener has already cloned the developerFields, the common file types should not clone it again.
- Add compile-time type assertion for Listener to satisfy decoder.Listener interface.
- Change Listener's options from pointer into concrete value. (reduce 1 alloc)

chore(filedef): clean up unnecessary developer-field-copy

---

cmd/fitconv/fitcsv/csv_to_fit.go
cmd/fitconv/fitcsv/fit_to_csv.go
cmd/fitprint/printer/printer.go
decoder/decoder.go
decoder/decoder_test.go
decoder/raw_test.go
encoder/validator.go
encoder/validator_test.go
profile/filedef/listener_test.go
proto/proto.go
proto/proto_test.go
proto/value.go
proto/value_test.go

DeveloperField is now consist of three fields: 
```go
type DeveloperField struct {
Num                byte 
DeveloperDataIndex byte 
Value              Value
}
```
This reduces redundant data compared to previous version that copied some values from `Field Description` message while missing the others (I found it was not complete). Instead of make a change to copy everything to DeveloperField that will make the size of the struct bigger (will affect performance, use a lot of memory space), let's make it simpler and when we need to get the reference details of the `DeveloperField`, let's just find the `Field Description` message reference using the combination of `Num` and `DeveloperDataIndex` in the prior messages.  Given that a 'Field Description' can serve multiple 'DeveloperField' …

refactor/perf(proto)!: simplify DeveloperField structure

---

decoder/decoder.go
decoder/decoder_test.go
encoder/validator.go
encoder/validator_test.go

Since we only need to know whether we have prior DeveloperDataId messages, we can just collect the DeveloperDataIndex value instead of creating full DeveloperDataId message that most likely we don't need it anyway, this will save memory allocation.

perf: remove unnecessary operations

---

cmd/fitconv/fitcsv/csv_to_fit.go
decoder/decoder.go
decoder/decoder_test.go
decoder/raw_test.go
encoder/encoder_test.go
internal/cmd/fitgen/profile/mesgdef/builder.go
profile/filedef/activity.go
profile/filedef/activity_summary.go
profile/filedef/blood_pressure.go
profile/filedef/course.go
profile/filedef/device.go
profile/filedef/goals.go
profile/filedef/listener.go
profile/filedef/monitoring_ab.go
profile/filedef/monitoring_ab_test.go
profile/filedef/monitoring_daily.go
profile/filedef/schedules.go
profile/filedef/segment.go
profile/filedef/segment_list.go
profile/filedef/settings.go
profile/filedef/sport.go
profile/filedef/totals.go
profile/filedef/weight.go
profile/filedef/workout.go
proto/proto.go

`a = slices.Clone(a)` can be simplified as `s = append(s[:0:0], s...)`, so we no longer need to depend to slices package just for cloning a slice. This is the default implementation in slices.Clone in go v1.22. Ref: https://github.com/golang/go/commit/b581e447394b4ba7a08ea64b214781cae0f4ef6c
Using `make+copy` is actually slightly more performant but it hurts the readability as the code become more verbose. The performance diff is relatively small, we probably don't need it unless we encounter a really edge case.
Here is the list the drawbacks: https://github.com/go101/go101/wiki/There-is-not-a-perfect-way-to-clone-slices-in-Go

chore: remove slices.Clone dependency

---

docs/usage.md
encoder/encoder.go
encoder/encoder_test.go
encoder/stream.go
encoder/stream_test.go
encoder/writebuffer.go
encoder/writebuffer_test.go
kit/bufferedwriter/doc.go

In most cases, we work with FIT protocol in the form of files, it is more make sense to use a buffer by default. We found that having to explicitly create a buffer makes the code more verbose without achieving any tangible benefits. In exceptional cases, when users don't want the Encoder to do buffering, users can direct the Encoder to do so by specifying `WithWriteBufferSize(0)` Option.

feat(encoder): implements write buffer

---

cmd/fitconv/fitcsv/fit_to_csv.go
decoder/decoder.go
decoder/decoder_bench_test.go
encoder/encoder.go
encoder/validator.go
profile/filedef/listener.go

Previously, we wrapped functional options with interface (`interface { apply(o *options) }`) following the [Uber style](https://github.com/uber-go/guide/blob/master/style.md#functional-options). While this style (arguably) provides more flexibility, this comes with a trade-off too: "arguments passed to interface's method typically be heap-allocated".
I don't think we need such flexibility in our code and [ordinary functional options](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) would be sufficient for our cases. Additionally, we make Decoder to reuse listeners' slices to reduce allocation needed. By doing this, we can get zero allocation when resetting Decoder and Encoder.
Here is the update and the benchmark regarding this change:
```js
goos: darwin
goarch: …
```

perf: optimize functional options

---

decoder/decoder.go
decoder/decoder_test.go

Previously, we allocate new object for every new message definition then removing the new object on reset, this cause decoder to create new object again and again. And on every new message definition, we allocate its slices as needed, so we need to re-allocate slice when the current slice's cap is less than the new one, here is the sample of `cap(mesgDef.FieldDefinitions)` when decoding `from_garmin_forums/triathlon_summary_first.fit`:
```go
LocalNum: 1, cap: 5   // alloc
LocalNum: 1, cap: 18  // re-alloc since 18 > 5
LocalNum: 3, cap: 13  // alloc
LocalNum: 3, cap: 14  // re-alloc since 14 > 13
LocalNum: 2, cap: 10  // alloc
LocalNum: 2, cap: 123 // re-alloc since 123 > 10
LocalNum: 2, cap: 49  // reslice
LocalNum: 2, cap: 47  // reslice
LocalNum: 2, cap: 41  // reslice
```
This PR …

perf(decoder): optimize decode mesage definition

---

.github/workflows/ci.yml

Always run CI on updates so we can catch any potential error when testing using latest Go version.

chore: always run ci on updates

---

cmd/fitactivity/combiner/combiner.go
cmd/fitprint/printer/printer.go
kit/datetime/datetime.go
kit/datetime/datetime_test.go

Breaking Changes:
- ToTime now accepts uint32 instead of any
- ToLocalTime now accepts time.Time instead on any and it is no longer allocate.
Since we use proto.Value, all timestamp will be represented as uint32 and in mesgdef's structures all timestamp will be represented as time.Time. There are no timestamp being represented as typedef.DateTime or typedef.LocalDateTime anymore. This way we can no longer need to convert the value to an interface, this will improve performance a little bit and we have more clear context when working with time.
Benchmark:
```js
goos: darwin
goarch: amd64
pkg: github.com/muktihari/fit/kit/datetime
│   old.txt    │               new.txt                │
│    sec/op    │    sec/op     vs base                │ …
```

perf!: update datetime package

---

.github/workflows/release.yml

Ensure the library can be compiled and is compiled using latest stable version of Go.

chore: update release workflow go version to stable

---

profile/filedef/listener.go
profile/filedef/listener_test.go

- Using array instead of map for fileSets field in `filedef.Listener` so we don't do allocation, slightly improve performance.
- Introduce `WithFileFunc` options that do not allocate when changing the predefined files, and it's now preferable than using `WithFileSets` that requires allocation.

perf: filedef.Listener change fileSets data type to array

---

proto/value_unmarshal.go
proto/value_unmarshal_internal_test.go

1. There is no need to use sync.Pool here, we know that the string will no longer than 255 and make slice of bytes using constant size does not escape to the heap, it typically stays on stack. This remove the overheard of retrieving array and writing to the heap.
```./value_unmarshal.go:245:13: make([]byte, 0, 255) does not escape```
2. Simplify trimming null string terminator when unmarshal string value.

chore: proto unmarshal value string remove sync.Pool

---

cmd/fitconv/fitcsv/formatter.go

`strings.Builder` typically stays on stack, there is no need to use sync.Pool

cli: fitconv remove unnecessary sync.Pool

---

proto/value.go
proto/value_test.go

The idea of using `interface{}` in `proto.Value` is to hold either a pointer to slice data to avoid reallocation the same slice since the slice is typically temporarily used and `proto.Value` is in the hot path (especially proto.Value's `Valid` method), or to store a Type since it can hold dynamic value (the implementation is similar to [go's log/slog.Value](https://github.com/golang/go/blob/27093581b2828a2752a6d2711def09517eb2513b/src/log/slog/value.go#L21-L36)). This, however, create an interface overhead when we try to store/load the data from it. 
Since we define all the Type that we use, we can ensure the safety of casting the value back and forth by storing a pointer directly as `unsafe.Pointer` type instead of putting it to an interface. Unlike `uintptr` that just an integer …

perf: proto.Value remove interface{} overhead

---

cmd/fitactivity/combiner/combiner.go

Every FIT activity start from zero distance, when we combine two or more FIT files, the Record's distance of next sequence of the FIT files need to be adjusted so that it becomes one continues activity.

cli: fix combine on distance not being accumulated

---

cmd/fitactivity/README.md
cmd/fitactivity/combiner/combiner.go

- `fitactivity` now supports combining split summary messages, so we don't lose any data unlike previous version that we omitted the messages completely. The resulting file can be uploaded to Garmin Connect without a problem.
- Fix bug on combine session calculation

cli: fitactivity now supports combining split summary

---

proto/value.go
proto/value_test.go

- Valid should also check the validity of uint_z's slice ([]uint8z, []uint16z, []uint32z or []uint64z)

fix: proto.Value's Valid method when handling slice of uint_z

---

encoder/encoder.go
encoder/encoder_test.go
encoder/stream_test.go
encoder/writebuffer.go

- Unnexpected _"encoder internal error"_ occurs when passing `io.WriteSeeker` as `io.Writer` since we forgot to early return. Previously, we treat an `io.Writer` that implements both `io.WriterAt` and `io.WriteSeeker`, such as `*os.File`, as `io.WriterAt` so users using `*os.File` does not affected by this bug. The bug only affects `io.Writer` that only implement `io.WriteSeeker`.
- Now `io.Writer` that implements both `io.WriterAt` and `io.WriteSeeker` will be treated as `io.WriteSeeker`. We change this to prevent wrong write on a `io.Writer` that is not empty (existing file) as we will aways write at offset 0 to update the header while offset 0 might not be our own content. By treating it as `io.WriteSeeker`, we can seek relative to EOF so we ensure that we write on our own data. This …

fix: encoder handling WriteSeeker

---

docs/usage.md
encoder/encoder.go
encoder/encoder_test.go

- Encoder: enable dynamic protocol version encoding based on the value in FileHeader. Now, Encoder by default will use protocol version in FileHeader for each FIT file, if it's not specified, it will use protocol version 1.0 (proto.V1).

feat: encoder enable dynamic protocol version

---

internal/cmd/fitgen/profile/mesgdef/mesgdef.tmpl
profile/mesgdef/climb_pro_gen.go
profile/mesgdef/course_point_gen.go
profile/mesgdef/gps_metadata_gen.go
profile/mesgdef/jump_gen.go
profile/mesgdef/lap_gen.go
profile/mesgdef/record_gen.go
profile/mesgdef/segment_lap_gen.go
profile/mesgdef/segment_point_gen.go
profile/mesgdef/session_gen.go
profile/mesgdef/split_gen.go
profile/mesgdef/weather_conditions_gen.go

- Remove invalid value check on degrees method as `kit/semicircles` already handle it.
- Clean up mesgdef.tmpl replace four space with one tab (\t)

chore: mesgdef clean up code

---

encoder/encoder.go
encoder/encoder_test.go

I just remember that we can seek from current offset, this way we ensure that we will write in our own data as we write relative to the current offset.

fix: encoder WriteSeeker now relative to current offset

---

cmd/fitactivity/README.md
cmd/fitactivity/combiner/combiner.go
cmd/fitactivity/combiner/combiner_test.go
cmd/fitactivity/concealer/concealer.go
cmd/fitactivity/main.go
cmd/fitactivity/opener/opener.go
cmd/fitactivity/reducer/reducer.go
cmd/fitactivity/reducer/reducer_test.go
go.mod
go.sum

This PR adds new feature "**reduce**" to reduce record messages in a FIT file to answer this issue #394 . 
This has 3 method to choose:
1. Based on GPS points using RDP [Ramer-Douglas-Peucker](https://w.wiki/B6U3).
2. Based on distance interval in meters
3. Based on time interval in seconds`
How we can interact with **fitactivity** CLI is also refactored for more structured commands (arguably easier to access and maintain). Some commands may differ, but they should be simple to follow. `cmd/fitactivity/README.md` file has been updated accordingly regarding the changes.

cli: refactor fitactivity

---

decoder/decoder.go
decoder/decoder_test.go

Related issue: #397 
The background of the problem that it solves declared here: https://github.com/muktihari/fit/issues/397#issuecomment-2337086333

fix: decoder should expand component only from a valid value

---

encoder/encoder.go

Previously on PR #415, we updated encoder's buffer size to **1537**, however we found that this size can be rounded into nearest golang's sizeclasses: https://go.dev/src/runtime/sizeclasses.go, which is **1536**.

perf: round encoder buffer size to nearest sizeclasses

---

profile/filedef/activity.go
profile/filedef/activity_test.go

"I find that these messages are commonly present in FIT files produced by Garmin devices. Having these fields will benefit us in manipulating known messages, especially when handling Split Summary messages, as these messages must be unique within each **split_type**.

feat: filedef add new messages in Activity File

---

cmd/fitactivity/combiner/combiner.go
cmd/fitactivity/combiner/combiner_test.go
go.mod
go.sum
internal/cmd/benchfit/go.mod
internal/cmd/fitgen/pkg/flagutil/flagutil.go
internal/cmd/fitgen/pkg/strutil/strutil_test.go
internal/cmd/fitgen/profile/mesgdef/builder.go
internal/cmd/fitgen/profile/untyped/fieldnum/builder.go
kit/scaleoffset/scaleoffset.go
profile/filedef/activity_test.go
profile/filedef/filedef.go

- Set minimal Go version to **v1.21** and drop _golang.org/x/exp_ dependency as `slices` package is available in v1.21 and we can define our own _constaints_ for numeric values without depend on that package. 
- Can not drop _golang.org/x/test_ since we still don't have replacement  to make Title Case (we use this package since strings.Title has been deprecated). Unit test for strutil.ToTitle is added in case in the future we want to create our own simplified implementation, we should pass the test.

refactor: set minimal go version to v1.21

---

decoder/decoder.go
decoder/decoder_test.go

- Now we only keep value when fieldNum is 253 and the value type is uint32. We no longer return  **ErrFieldValueTypeMismatch** error when the fieldNum 253 is not an uint32, as there is no documentation that say 253 must be for timestamp and we found some old message may have timestamp for other fieldNum such as **CoursePoint** and **Set** messages, although these messages may be created before the rule was put in place. We think that maybe some manufacturers use this fieldNum for something else as well. We don't think returning error will add any value.
- Some errors are deleted or make private;  **ErrDataSizeZero** is deleted and an **ErrNotFITFile** will be returned instead when **FileHeader's DataSize** is zero.

refactor!: decoder sentinel errors

---

proto/value_unmarshal.go
proto/value_unmarshal_internal_test.go
proto/value_unmarshal_test.go

Strings may contains padding bytes. Previously, I thought that the padding only consist of zero bytes, but it turned out the padding bytes can be vary for example **workout_step's notes (array: false)**: 
Since string in utf8 is terminated by zero, we cut the value up to zero. Now we will omit invalid utf8 character as well, since it does not comply with FIT's string spec.
It was first discovered when handling files from this thread:
https://forums.garmin.com/developer/fit-sdk/f/discussion/383991/my-fit-file-that-i-combined-won-t-upload-to-garmin-connect#pifragment-1304=1

fix: proto UnmarshalValue on handling string padding

---

decoder/decoder.go
decoder/decoder_test.go
decoder/raw.go
encoder/encoder.go
encoder/encoder_test.go

- decoder: Compressed timestamp header message has local message type 0-3 positioned at bit 5-6 (note: normal message has local message type 0-15 positioned at bit 0-4). Bit 6 overlap with proto.MesgDefinitionMask, the only thing that differentiate them is the bit 7.  So we must take bit 7 into consideration when checking the header type, is it message definition or is it message data. Since only message has value at header bit 7, we we must include proto.MesgCompressedHeaderMask to do mask, only then we can get the correct header type.
- encoder: Previous implementation of timestamp compression has a bug, where we always has timestampReference 1. It should  have only been updated when Rollover Event occurs.

fix: handle compressed timestamp

---

cmd/fitactivity/main.go
cmd/fitconv/fitcsv/csv_to_fit.go
encoder/encoder.go
encoder/encoder_bench_test.go
encoder/encoder_test.go

At the beginning, I thought that when using compressed timestamp, we can only use local message type zero, but after a year, I re-read the documentation again, it turns out that we can use 0-3 local message type. 
Message (Data) 's Header bit layout: 
| Bit   | Value  | Desc                        |
| ----- | ------ | --------------------------- |
| 7     | 1      | Compressed Timestamp Header |
| 5 – 6 | 0 - 3  | Local Message Type          |
| 0 - 4 | 0 - 31 | Time Offset (seconds)       |
With this being implemented, I think how FIT SDK handle compressed timestamp is finally completed. This change comes with breaking changes, dropping **WithNormalHeader** and **WithCompressedTimestampHeader** encoder options, replaced with **WithHeaderOption**

feat!: encoder compress timestamp with multiple local message type

---

cmd/fitactivity/README.md
cmd/fitactivity/main.go

- all commands: flag **--compress** now accept **uint8** instead of bool
- combine/remove: flag **--nums** is renamed to **--mesgnums**

cli: fitactivity enable compressed timestamp header with multiple local message type

---

encoder/encoder.go
encoder/encoder_test.go
proto/validator.go
proto/validator_test.go

We don't need getter and setter for field that can be changed directly.

fix!: protocol validator export protocol version field

---

cmd/fitactivity/README.md
cmd/fitactivity/combiner/accumulator.go
cmd/fitactivity/combiner/accumulator_test.go
cmd/fitactivity/combiner/combiner.go
cmd/fitactivity/combiner/combiner_test.go
cmd/fitactivity/main.go

Previously, we only accumulate Record's `distance`, but in reality, messages may have fields requires accumulation as well, such as Record's `accumulated_power`. We should dynamically find and accumulates those values.

fix: fitactivity combine should accumulate all the accumulable values

---

encoder/encoder.go
encoder/encoder_test.go
encoder/stream.go
encoder/stream_test.go
encoder/validator_test.go
proto/validator.go
proto/validator_test.go

Validating messages early give several advantages:
1. If invalid message occurs, we can return early without doing unnecessary works such as marshaling, calculate CRC or even do a syscall to write to the file.
2. If normal writer is given (a writer without offset writer capability), the encoding speed is improved by geomean 16% since  we don't need to validate messages twices. Benchmark:
```go
goos: linuxl goarch: amd64l pkg: benchfitl cpu: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
Encode/muktihari/fit_raw-4   93.57m ± 8%   74.63m ± 3%  -20.24% (p=0.000 n=10)
Encode/muktihari/fit-4       157.2m ± 7%   136.7m ± 2%  -13.01% (p=0.000 n=10)
geomean                      121.3m …
```

perf: early validate all messages before encoding

---

cmd/fitconv/fitcsv/csv_to_fit.go
cmd/fitconv/fitcsv/formatter.go

- Remove quote " char and other unprintable char when convert fit to csv
- Fix line and col wrong positioning, and add verbose error message

cli-fix: fitconv remove quote char and unprintable chars in csv

---

decoder/decoder.go

Previously, d.fieldDescriptions was resliced on reset, resulting d.releaseTemporaryObjects to do nothing regarding that field so the pointers (if any) will be keep until next decoding process reaching the previous slice index then replacing the 
value.
In general, this should not be a problem since the values will be replaced anyway when we do decode again, and the pointer will eventually be released at some point or when the decoder is no longer used (garbage-collected), but it becomes nondeterministic, so let's fix it.
We can move the resetting of d.fieldDescriptions and d.developerDataIndexes to d.releaseTemporaryObjects instead of in d.reset, since these fields only changes during decoding messages.

fix: decoder should clear the pointers before reslicing

---

profile/filedef/activity.go
profile/filedef/activity_test.go

- Add sports messages in Activity File. FIT files produced by Garmin devices typically has this message, and it can be multiple sports messages such as when doing a Triathlon.
- Manually put messages that, we know upfront, have no timestamp at the beginning of the resulting messages, we don't need to include it to be sorted. This will save a bit of resource and time.

feat: filedef activity file add sports and update its sorting

---

profile/filedef/segment.go

Hi folks! 
Thank you for pretty handy SDK. I found that currently a segment file can have the only one leaderboard entry. This is not expected behaviour. Multiple leaders should be supported by design. In the case of Strava segment it is quite often that a segment has atleast three leaderboard entries like KOM, QOM and Personal Best. 
This PR makes possible to add multiple leaderboard entries to a segment file.
Keep going!
Regards, Ilya

fix: segment file can have multiple leaderboard entries

---

cmd/fitprint/printer/printer.go
decoder/accumulator.go
decoder/bits.go
decoder/bits_test.go
decoder/decoder.go
decoder/decoder_test.go

Previous implementation of component expansion does not accommodate containing field's value more than 32 bits. This results in expanding incorrect components for  messages that has more than 32 bits such as "Hr" `event_timestamp_12` (up to 120 bits) and "RawBbi" `data` (up to 240 bits). 
By design, field's value requiring expansion can hold up to 255 bytes (2040 bits) data, this is obviously way more bits than Go's primitive single value can hold. To handle this, I implement new type "bits" struct that can store up to 2048 bits data, enable us to do bitwise operation over it for component expansion.
To test the correctness, I use sample data from _"testdata/from_official_sdk/activity_poolswim_with_hr.csv"_, as it contains **96 bits data** to be expanded and the new implementation …

fix: decoder component expansion

---

decoder/bits.go

- We should compare whole store array to check whether it has run out a value (reach zero).
- We should not early break as the store may still contains valid value in certain index (edge cases).

fix: decoder bits on Pull method

---

proto/value.go

- Since [Go v1.21.0](https://tip.golang.org/doc/go1.21), the compiler is smart enough to do type inference for generic slices, we don't need to do `[]E(s)` anymore.
- For `proto.SliceBool` since we only accept `[]typedef.Bool`, this function does not need to be generic.

chore: simplify proto value

---

factory/factory_gen.go
internal/cmd/fitgen/factory/builder.go
internal/cmd/fitgen/profile/mesgdef/builder.go

Scale and offset do not apply for field that has more than one components, set it to default scale 1 and offset 0.

fix: fitgen's factory and mesgdef on evaluating scale offset

---

decoder/decoder.go
decoder/decoder_test.go

Hr message's `event_timestamp` is an []uint32 and it's accumulable values. Previously, decoder only accumulate single value and discarding slice value, this PR fix it.

fix: decoder on accumulating slice values

---

decoder/decoder.go
decoder/decoder_test.go

If a field has only one component and its value is not an invalid value, expand it even if its value is zero e.g. `speed (0)` -> `enhanced_speed (0)`.

fix: expanding field that has only one component

---

decoder/decoder.go
decoder/decoder_test.go

This PR update component expansion logic on handling edge case such as when a message already has field with the same field number as the expanded field candidate (component field). For such cases, the value of the field will be updated, including the component expansion that is propagated.
For a case like this, typically, the value of the field is the same with the value of the expanded field. For example a record message has speed and enhanced_speed with the same value before the expansion, after the expansion the value will be the same.

fix: decoder component expansion on handling edge case

---

decoder/bits.go
decoder/bits_test.go

- Now we only check whether bits' store has reach zero. The bits validity checking is removed since we already check the value validity in decoder and The bitsize checking is also removed since it's not FIT files related but it's an implementation detail of Profile.xlsx.
- The zero size of bits is now reserved as global variable, this makes comparing bits to its zero value a bit faster.

chore: simplify decoder's bits

---

encoder/encoder.go
encoder/encoder_test.go

- Move validations that are still reside in `encodeMessages` into `validateMessages` for consistency and separation of concerns.
- Improve encoder's test readability by moving table test creation from outside test function into inner test function.

chore: move validations in encodeMessages to validateMessages

---

decoder/bits.go

Checking zero value is unnecessary as it will return zero anyway. It arguably only make Pull slightly faster for pulling the last value but its make Pull slower for the entire pulling process. 
By reducing this instruction, compiler can inline Pull method. 
```
before:
./bits.go:94:6: cannot inline (*bits).Pull: function too complex: cost 86 exceeds budget 80
after:
./bits.go:92:6: can inline (*bits).Pull with cost 79 as: method(*bits) func(byte) uint32
```

chore: remove bits' store zero value check

---

.github/dependabot.yml
.github/workflows/scorecard.yml
SECURITY.md

The project has reach a "stable" phase as the features, more or less, have been completed. The project is now entering maintenance mode. I don't think we need to update the dependencies too often for both GitHub Actions or Go modules since we will rarely push new PR compare to before. New releases might be less frequent as well unless there is a Profile update, bug fixes or improvements. So I update schedules from weekly basis to monthly basis.
SECURITY.md: 
- Change the doc that we are now scanning on monthly basis.
- Change the word "ensure" to "minimize" as the word "ensure" is tricky here. All we can do is minimizing risk, not eliminate it entirely.

chore: update workflow schedules

---

proto/proto.go
proto/proto_test.go
proto/value.go
proto/value_test.go

There are two objectives that this PR solves by implementing [fmt.Formatter](https://pkg.go.dev/fmt#Formatter) for `proto.Field` and `proto.Value`.
1. Reduce gotcha when printing `proto.Value`, as `proto.Value` has the same implementation of [fmt.Stringer](https://pkg.go.dev/fmt#Stringer), but we treat it as a special case method to retrive string value, rather than the underlying value formatted as a string. Example:
```go
val := proto.Uint8(10)
fmt.Println(val)       // We might expect 10, but it prints "" since it's not a string
fmt.Println(val.Any()) // Previous workaround, we must call Any() method
```
And thing gets trickier when we print a type containing `proto.Value` such as `proto.Field` or maybe if we print the whole `proto.FIT` itself, as it will trigger `fmt` to call …

fix(proto): implement fmt.Formatter for Field and Value

---

proto/value.go
proto/value_marshal.go
proto/value_test.go

In general, I value simplicity over cleverness. However, in this case, I trade some simplicity for a bit of cleverness to gain a considerable performance boost. Here is my justification:
In the previous implementation, we need one more 1-byte field, `typ`, just for storing a type, resulting _one-word_ penalty for every single `Value` we have. In 64-bit machine, _one-word_ is 8 bytes, so the size of the `Value` will be 8 + 8 + (1 + 7 padding byte) = 24 bytes. If we use this SDK to handle a really large fit files, such as from a ultra-long-run or ultra-triathlon race, the _one-word_ penalty will be significantly multiplied as we have way more messages. And imagine when this SDK is used to handle multiple fit files at once.
```go
// Struct before, size 24 bytes.
type Value struct { 
_ …
```

perf(proto): reduce Value's size by one-word

---

decoder/decoder.go
decoder/decoder_test.go

- When `Size < Basetype's Size`, decoder must retrieve value as bytes (previously undefined behavior)
- Convert bytes to its corresponding value must respect endianness (previously use Little-Endian)
chore:
- Simplify converting `BaseType` to `ProfileType` when handling unknown field, since the value of `ProfileType` is the same as `BaseType Number` we can cast it directly.

fix(decoder): handling poorly encoded fit

---

proto/value.go
proto/value_test.go

There is a bug in #522 new value implementation causing slice accessor to access arbitrary memory (security issue).
When we do this, we expect that `result` will be `nil` but it's not:
```go
value := Uint64(uint64(TypeSliceUint8)<<vshift | 1) // <- 1 is the len of the slice
result := value.SliceUint8() // <- we expect nil
```
It may return `[]uint8{0}`, `[]uint8{255}` or similar value; where 0 or 255 is an arbitrary value that the pointer is pointing to. Because we don't check the value correctly.
Moreover, this following code may cause `SIGSEGV: segmentation violation`
```go
value := Uint64(uint64(TypeSliceUint8)<<vshift | 1000_000)
result := value.SliceUint8() 
```
This PR ensure that we don't allow such cases.

fix(proto): value slices accessor

---

decoder/decoder.go
decoder/decoder_test.go
decoder/raw_test.go
docs/usage.md
encoder/encoder.go
encoder/encoder_test.go
kit/hash/crc16/crc16.go
kit/hash/crc16/crc16_test.go

It has been over a year since the creation of this Go SDK, and I don't see the need for a custom table for crc16. The FIT protocol itself has been around for 15 years, yet the checksum table remains unchanged nor having other variants.
Removed Items:
- constant Size
- type Table
- func MakeFITTable
- func New no longer receiving params

refactor(crc16)!: simplify code

---

encoder/encoder.go
encoder/validator.go
proto/proto.go
proto/proto_marshal_test.go
proto/value.go
proto/value_test.go

Move func `Sizeof` as Value method named `Size`. The context of size calculation on only applies to Value, so it makes more sense to have it as method instead of function. This make `proto` package cleaner as well.

refactor(proto)!: change func Sizeof into Value method named Size

---

cmd/fitactivity/main.go
cmd/fitconv/fitcsv/csv_to_fit.go
cmd/fitconv/main.go
cmd/fitprint/printer/printer.go
encoder/encoder.go
encoder/encoder_test.go
encoder/stream.go
encoder/stream_test.go
encoder/validator.go
encoder/validator_test.go
internal/cmd/fitgen/profile/factory/factory.tmpl
internal/cmd/fitgen/profile/mesgdef/builder.go
profile/factory/factory_gen.go
proto/validator.go

- Remove words like "could not" and "failed" on error wrapping, it's error anyway so it's expected that we "could not" do something or the operation is "failed".
- Change wording for some error wrapping for more concise error message.
- encoder: remove `ErrWriterAtOrWriteSeekerIsExpected` and `ErrNilWriter`, introduce `ErrInvalidWriter` instead
- encoder: make some sentinel errors private since the error is not an expected error. `ErrMissingDeveloperDataId` and `ErrMissingFieldDescription` is being kept in case when users receive these errors, they want to fallback the operation to encode using proto.V1 or to abort the operation altogether. `ErrMissingDeveloperDataId` is being used by fuzz test.

refactor!:  make error wrapping more concise

---

encoder/encoder.go
encoder/encoder_test.go
encoder/stream.go
encoder/stream_test.go
encoder/validator.go
encoder/validator_test.go
fuzz_test.go

After careful consideration, I decide to make sentinel errors into private errors. I don't think we can use it to take a specific action with those errors, I think it's uncommon and maybe on special case only. For example, `ErrInvalidWriter` is actually not needed since user can just check the writer before passing to the encoder. Next case is `ErrMissingDeveloperDataId`, users are expected to write good fit's messages, having that error does not help users to take specific action since users still need to edit fit's messages before proceeding again.

refactor(encoder): make errors private

---

cmd/fitconv/fitcsv/csv_to_fit.go
docs/usage.md
encoder/encoder.go
encoder/encoder_test.go
encoder/stream.go
encoder/stream_test.go

`StreamEncoder()` method in my opinion is less discoverable, it's a bit weird to instantiate new different object through a method. The new func constructor `NewStream` is explicit and clearer.

refactor(encoder)!:  add NewStream to replace StreamEncoder() method

---

internal/cmd/fitgen/lookup/lookup.go
internal/cmd/fitgen/profile/factory/builder.go

Factory builder was importing `typedef` package, resulting mismatch data lookup since fitgen is already compiled with previous code generated `typedef` while at runtime it expects updated version of that package.

fix(fitgen): factory builder should not import generated package

---

decoder/decoder.go
decoder/decoder_test.go

We no longer need array of pointers that points to other array data just to check valid message definition for upcoming data, instead we can just check the original data with `header != 0` since valid message definition's header will always has >= 64 value. We only need to reset header to zero on reset.
Message definition's fields and developer fields slice allocation are moved near loop assignment to ensure that we only allocate when we actually need it and we don't want to allocate when it just simply return error afterward.

chore: simplify decoder local message definitions storage

---

decoder/readbuffer.go

Thanks for the great library!
Fixed the comparison of int32 with MaxUInt32. Breaks the 386 build.
https://github.com/muktihari/fit/blob/f1f12ed2fc900cd2d2b77060e3c5d1611f5d2fbd/decoder/readbuffer.go#L49-L56

fix: build issue on 386 arch
