README.md
cmd/fitactivity/README.md
cmd/fitactivity/combiner/combiner.go
cmd/fitactivity/concealer/concealer.go
cmd/fitactivity/finder/finder.go
cmd/fitactivity/main.go
cmd/fitactivity/opener/opener.go
cmd/fitconv/README.md
cmd/fitprint/README.md

fitactivity program enables us to combine multiple FIT activity files into one continuous FIT activity, as well as conceal GPS positions for specific start and end distances.

feat(CLI): add new fitactivity CLI

---

cmd/fitactivity/README.md

miss typo from previous PR,  let's call it a day then 😅

docs(fitactivity): fix typo in README.md

---

README.md
cmd/fitactivity/README.md
cmd/fitactivity/concealer/concealer.go
cmd/fitactivity/main.go
cmd/fitactivity/opener/opener.go

- now start and end positions in all lap messages are removed when conceal option is specified
- improve conceal record positions logic
- update README.md

feat(cli): update on fitactivity conceal logic

---

.github/workflows/fitgen.yml

- Clean up code
- Change token so to enable triggering CI.yml workflow after commit is pushed to PR

chore: update fitgen

---

docs/usage.md
profile/filedef/course.go
profile/filedef/doc.go
profile/filedef/listener.go
profile/filedef/workout.go

- now listener can accept multiple common file types during decoding chained FIT file
- update usage.md documentation related to common file type

feat!: filedef listener now support multiple common file types

---

decoder/decoder.go
decoder/decoder_test.go
encoder/encoder.go
encoder/encoder_test.go

The main goals of having context is to cancel the process as soon as we can when the context is canceled or the deadline is exceeded to save resources. This PR should be sufficient to do the logic without altering existing code that much, since it's only one layer above it. Things to note, on Encode for example, when the context is canceled, some bytes written to the `io.Writer` might be truncated, but it will end with a proper message since we try to stop the process per a single message encoding. It's up to the user to clean up the underlying writer as necessary. If user does not want the file to be truncated, they need to use `Encode()` instead.
close #72

fix: context propagation issue

---

decoder/decoder.go
decoder/decoder_test.go

benchstat:
```js
goos: darwin
goarch: amd64
│   old.txt    │              new2.txt               │
│    sec/op    │   sec/op     vs base                │
CheckIntegrity-4   18.59m ± 11%   16.57m ± 1%  -10.82% (p=0.007 n=10)
│  old.txt   │              new2.txt              │
│    B/op    │    B/op     vs base                │
CheckIntegrity-4   314.0 ± 4%   149.0 ± 6%  -52.55% (p=0.000 n=10)
│  old.txt   │              new2.txt              │
│ allocs/op  │ allocs/op   vs base                │
CheckIntegrity-4   9.000 ± 0%   1.000 ± 0%  -88.89% (p=0.000 n=10)
```

perf: reduce B/op and allocs/op

---

decoder/decoder.go
decoder/decoder_test.go
docs/usage.md

- Add Discard method to efficiently discard a FIT file sequence in a chained Fit file.

feat(decoder): add Discard method

---

.github/workflows/fitgen.yml

Any input, in this case PR's comment, should be treated as untrusted input and should not be placed directly on run. By placing it on environment variable, the input will be sanitized. 
ref: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections

chore: update fitgen.yml to prevent script injection attack

---

proto/value.go

proto: update proto.go code documentation

---

decoder/decoder.go
decoder/decoder_test.go
decoder/readbuffer.go

- Fix n bytes counter mismatch on decode file header
- Make ErrCRCChecksumMismatch more verbose in CheckIntegrity
- Simplified readbuffer's ReadN

fix(decoder): n bytes counter

---

encoder/encoder.go
encoder/encoder_test.go
encoder/stream.go

- Make naming `FileHeader` consistent across all functions and comments to avoid confusion with `header` for message's header
- Rename encodeHeader to encodeFileHeader, updateHeader to updateFileHeader
- Simplify encode functions logic, remove unnecessary parameters such as `w io.Writer` in `encodeMessage`
- Format comments to not exceed 120 character for better readability. 
- Aligning options's struct memory.
- Re-order Encoder's methods for better readability.

chore: clean up encoder

---

decoder/decoder.go
decoder/decoder_test.go

Discussion: https://forums.garmin.com/developer/fit-sdk/f/discussion/355554/how-to-determine-developer-field-s-value-type-is-a-string-or-string
- When decoding string value for `DeveloperFields` and `unknown Fields`, we no longer treat it as []string, instead fallback to FIT Protocol rule on string: decoder will determine it by counting how many valid string in bytes. if valid strings > 1 then it's a `[]string`, otherwise a `string`
- Clean up some code.

fix: decoder on handling string, mainly on developer fields

---

profile/filedef/listener.go

- Change listener's pool type from proto.Message to []proto.Field as we only use the pool for Fields, this will reduce the memory used by the pool channel since sizeof `proto.Message` is 56 bytes where a slice is only 24 bytes.
- Pick optimal value for default channel buffer based on benchmark, we have few candidates [8, 16, 24, 32, 64, 128, 256, 512, 1000 (previous default)], the values are actually just arbitrary number, it does not have special meaning of why it's a multiple of 8. Let's just take a look on these benchmark result:
```js
goos: darwin | goarch: amd64 | pkg: benchfit
│     8.txt     │                16.txt                │               32.txt                │                64.txt                │               128.txt …
```

perf: optimize channel buffer and object pooling

---

encoder/encoder.go
encoder/encoder_test.go

Previously, time-offset in message's header was cleared and replaced with zero resulting corrupted FIT file output, this PR fix that issue.

fix: compressed timestamp header wrong header value

---

profile/filedef/activity.go

- `SegmentLap` should have been `SegmentLaps` (plural) since it's a slice.

fix!: filedef's activity field SegmentLaps typo

---

.github/workflows/fitgen.yml

Ensure the library can be compiled and is compiled using latest stable version of Go.

chore: update fitgen workflow go version to stable

---

decoder/decoder.go

- Remove redundant fields `mesgListeners` and `mesgDefListeners` since it share the same element as fields in options.
- Realign decoder to reduce struct size.
- Clean up code and update documentation.

chore: simplify decoder struct

---

decoder/decoder.go

Potential memory leaks only applies when Decoder is being reused, release these temporary objects created during a single decode process, so the memory can be claimed as soon as possible:
- `d.fieldDescriptions` and `d.messages` will no longer needed after Decode method returns, it need to be released.
- Both `Field` and `DeveloperField` have `Value`; and `Value` has interface{} that may hold
a pointer to a string/slice that won't be released until we stop referencing them.
- `Field` has a pointer to `FieldBase`, unlike `known Field` that points to factory's `FieldBase`,
an `unknown Field` points to new temporary `FieldBase` object that need to be released as well.

fix: decoder potential memory leaks when decoder is being reused

---

encoder/encoder.go
encoder/encoder_test.go

Previously, when using compress timestamp header for non-offset-writter (w io.Writer that does not implement either io.WriterAt or io.Seeker), encoder will always place the timestamp back to index zero after the calculation process completed, this PR fix it to place the timestamp back to its original index.

fix: encoder early check restore timestamp

---

internal/cmd/fitgen/profile/mesgdef/builder.go
internal/cmd/fitgen/profile/mesgdef/mesgdef.tmpl
profile/mesgdef/ant_channel_id_gen.go
profile/mesgdef/bike_profile_gen.go
profile/mesgdef/connectivity_gen.go
profile/mesgdef/course_point_gen.go
profile/mesgdef/device_info_gen.go
profile/mesgdef/device_settings_gen.go
profile/mesgdef/dive_alarm_gen.go
profile/mesgdef/dive_apnea_alarm_gen.go
profile/mesgdef/dive_settings_gen.go
profile/mesgdef/event_gen.go
profile/mesgdef/exd_data_concept_configuration_gen.go
profile/mesgdef/exd_data_field_configuration_gen.go
profile/mesgdef/exd_screen_configuration_gen.go
profile/mesgdef/file_id_gen.go
profile/mesgdef/goal_gen.go
profile/mesgdef/gps_metadata_gen.go
profile/mesgdef/hrm_profile_gen.go
profile/mesgdef/max_met_data_gen.go
profile/mesgdef/monitoring_gen.go
profile/mesgdef/record_gen.go
profile/mesgdef/schedule_gen.go
profile/mesgdef/sdm_profile_gen.go
profile/mesgdef/segment_file_gen.go
profile/mesgdef/segment_id_gen.go
profile/mesgdef/three_d_sensor_calibration_gen.go
profile/mesgdef/training_file_gen.go
profile/mesgdef/user_profile_gen.go

- ToMesg should always append field with bool type regardless its value
- Fix mesgdef's builder on creating comment for array value
- Remove unnecessary type cast for type that ends with z (e.g. uint8z)

fix: mesgdef ToMesg on handling bool value

---

README.md
cmd/fitactivity/README.md

- Remove _OpenSSF Best Practices_ badge as it can be viewed from the _OpenSSF Scorecard_ badge's link.
- Update Motivation description and fitactivity description

docs: update README.md

---

cmd/fitactivity/README.md
cmd/fitactivity/concealer/conceal_test.go
cmd/fitactivity/concealer/concealer.go
cmd/fitactivity/main.go

Previously, we remove GPS Positions from Laps completely, now we update the GPS Positions to match the new desired positions based on the conceal result.

cli: fitactivity improve concealer

---

cmd/fitactivity/main.go
cmd/fitactivity/opener/opener.go
cmd/fitactivity/opener/opener_test.go

- Implement context propagation
- Auto clean up output file when encode return with error.

feat: fitactivity implement context propagation

---

encoder/encoder.go

Previously, for carrying out an encoding process, we defined array as buffer with size of 130051 (130Kb). The size is calculated from maximum bytes need from a message: 
```
```
If we look at the Global Profile (Profile.xlsx), The message that has the most fields is Session having 153 fields, this is 102 less fields than the maximum spec and not all field will be used since some of them are sport-specific making it more less that 153 fields and not all manufacturers use developer fields, even if they do only small number that being utilized. So having 130051 upfront does not make sense here.
In real world, I found out that most of FIT activity files produced from various brands, such as Garmin, Bryton, Coros, etc, are only using **less than 256 bytes**.
I think using array is less …

perf: optimize encoder buffer size

---

proto/value.go
proto/value_marshal.go

- Update (Value) SliceBool code documentation: []bool into []typedef.Bool
- Simplify string len counting in proto.Sizeof
- Update switch's cases ordering to match proto Type's constants order for consistency.

chore: clean up proto Value code

---

decoder/decoder.go
decoder/decoder_test.go

- PeekFileId must check only the first message, if it's not a FileId, return an error.
- Decoder's sequenceCompleted is now removed

fix: decoder PeekFileId must check only the first message

---

profile/filedef/listener.go

filedef's Listener is designed to be reusable and can be used with sync.Pool. By clearing any pointer references in fields' pool (poolc) on every Close(), this cleans Listener before being put back to the pool, so any object that was previously being referenced such as proto.FieldBase created for unknown fields or field.Value containing a pointer to a slice can be garbage-collected on the next GC cycle.

pref: clear filedef's listener fields' pool on Close

---

decoder/readbuffer.go
decoder/readbuffer_test.go

The purpose of this PR is to simplify the mental model needed to understand the code.
- remove `newReadBuffer` constructor function since it's not being used. We don't construct readBuffer directly on decoder but we construct it during `Reset()` method.
- remove `Size()` method since its not being used except on test.
- remove ambiguous variable assignment `cur` and `last` with `reservedbuf` during `Reset()`. We can just assign it with 0 since `cur` and `last` will be replaced anyway during `ReadN()` invocation. The `reservedbuf` assignment does not add any value.
- update code documentation

chore: readBuffer remove unused func and method

---

proto/value.go
proto/value_test.go

Early return when one value is valid rather than iterate the whole slice data.

chore(proto): simplify Value's Valid method

---

cmd/fitactivity/combiner/combiner.go
cmd/fitactivity/combiner/combiner_test.go

cli(fitactivity): total timer time should be no gap

---

cmd/fitactivity/README.md
cmd/fitactivity/combiner/combiner.go
cmd/fitactivity/combiner/combiner_test.go

cli(fitactivity): temporary fix for total training effect

---

decoder/decoder.go
decoder/decoder_test.go

- We don't need `sync.Once` since Decoder's methods are not expected to be accessed concurrently, decoding is a sequential process. This remove unnecessary mutex locking.
- Remove redundant `Factory` field, instead use `options.Factory`. This prevent accidental wrong assignment and also this reduce Decoder's struct size.
- Reorder Decoder fields to optimize memory alignment.
- Remove unnecessary  context checking on every step, checking on decoding messages is enough.
- Remove redundant error checking, `decodeFileHeaderOnce` is already check the error for us.

chore: simplify decoder internal code
